name: deploy-project
on: 
    push:
        branches: 
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: appleboy/ssh-action@v1
              with: 
                host: ${{ secrets.MY_SERVER_HOST }} # 要部署的服务器的host
                username: ${{ secrets.MY_SERVER_USERNAME }}
                password: ${{ secrets.MY_SERVER_PWD }}
                script: |
                    cd /home/ubuntu/web_project/pet-mall
                    git pull github master
                    pnpm install
                    pnpm build:server
                    pm2 restart pet-mall-api
                    pnpm build:client
                # pnpm build:admin 当前我的服务器性能不太好，所以暂时不构建admin，否则卡死
                # 服务端之前启动api项目的pm2的命令： 
                # pm2 start npx --name pet-mall-api -- cross-env NODE_ENV=production H5PAY_APP_ID=支付appID H5PAY_APP_KEY=支付appKey node ./apps/server/dist/main
                # 记得 配置nginx 代理 

